version: "2"
services:
  db:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/mongodb-trips:/data/db
    ports:
       - 27017:27017
    command: mongod --storageEngine wiredTiger --smallfiles --logpath=/dev/null