apiVersion: v1
kind: Secret
metadata:
  name: cestaky-secrets
data:
  # base64 encoded key.pem
  server-private-key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBc25SelJJWVg3
    ZDdMRnFwWnA5S2c5UU5XRkxnZTlPNEs0UmZiaU1sWElidCtnQzE0CnFLQXJmOXMybFkyMElhOW1K
    TGgrOW15MlhTYjY4L0NCVDg3aWRwVjZzdWorOHNsb3FlNXJVN1k0S2JsUzc5RUcKNkJzdVFsZDBL
    Y2h0V1lxdXlkU29YbEVQYVovQWhBaGZpT3N6TnVPSnVHNHdzYXZIUDYrU05hVnJtM3lQbDVZRwpN
    eXRpUFlQSG1ZREhIdS9UTGhQK3pTa1I1YWJubTNva0Y4cDgzTTR4VmpCRXFJZEZRSzUwejFlcWJu
    WFM5UTl1CkZjWWtQTUtlOExiUm0xY28rc2NUdktjcG9ySFE4eHo1Z3J4M1F3dTd4Z2RPODRsSm5y
    M3YzRzQ3bXBzZHlUR1UKVnFVMDRQblVSMjc3M0c0VlYwcEtiTlVycVRZczNsR01hSHlrWVFJREFR
    QUJBb0lCQUdOVzA3dTNjYWFtdVNMNgozVUhBekh6WHlKbHNEVCtISzJNMkpxMDBkMTU5d3VPVGJI
    RmlDQlQ2Y0o0NzdhUTZ3WDk3ZktHc3pxOTRQWWFCCndWb3Q3bjdZb3g3bytOTXFMeXM1WDJHUU5C
    OTEzS2RIRXJNdVBrZ0w2c3cvbUMrYU5jYUFyT0VqK3BKdnJYbFMKTit3K0VacGllNDNCT1RZT1M3
    STJDQXY0ODdmdlpjYk01cWluZGlsckE2M2RQWUVxRFlZWnV3OGFjb1JKaGw4RApZK2UveEtkcjly
    M2ZQelNobWY0TFYrRnRYREhQQ1QzMklTWXBzMVVxaFNTM1ZtWUR4czI5QTdObmVHcDFpQzMyCmZD
    ZDBFcEE2OUpFT0VNdzh0RERsMGswNEFGTG1zdm12a2tGbHFLUW5FakgzTG1kSURUUnBhMkVXUXZu
    K1MxdmIKWk8wQ3FXRUNnWUVBN0kvb3RldUdkd2c1bFNjbmJGR2dxN3ZGeWhBNjBTRTN6aHg3ZGZG
    ZFgzbGRvLytEeFlqRgpYNkZWaXZIUDNYRmdEK3lmK2doQjcxRVUzdjdEV3lsTU1acVZUMWNIVHk4
    V0tWSlR3bnB4NG9vcjVjSXJKNHZJCkh4YUNUcnNoKy9aSGs0ZXlOc2Q5MGtKVG9Qd2xuMm05Ty8v
    WDlPQlJvYUJmT1FFQnBjeUdra1VDZ1lFQXdSNUEKNDJRRlVKWDkrQTdJZTV5RDFZYnc4SmgxZllm
    Z0o4c1RtVmZmRmF6YzVWbFRqYlRoWXJaN0JIZ1JVMTkvd1hSQQpYRU00UlVPM2pyOEVZVmVvTnhF
    Z1Z5bzVGTTZKWjl3VGlqYlhjWHJZbHJUSlE4ZlNyWTh4b09tSmtWZm0vRWd3CkpHUC91VmJQUDVF
    Y2xzeXBZUnM0a2dUcXNPVE4vVDBGV0ZPVE9XMENnWUEySnJNa2dhZWtNOVBLbXMzaGM4WU4KeWN2
    NjkwQWZnelVkRDFRTHFaYXdOajREUG9oUmZYK0E1cE9JWE5ZeVlMT1dzWm5sU0dLZmY3WUJYZHdt
    VUF2TApCeEhLdWFkSXJ3U3ByTmpUbWVmYjdia2l2UkhYMloyVDBEbEFBSUpGQlJsWllpU2ZlWWNK
    ekhrTVR1dmwwL1NuCmVXZGIvTVZ5OUIwWUZXemxJUzVrNlFLQmdEQUl3MkVMNXRxRmhGY243aXY0
    NFQzQ1E3bkVZaXpvR0JRdHllRXgKWHhhNEdYV2VnMDdTOStDaXZQUituT2ljNzEwQittUTRnQTJT
    YTF6QkhHak44ZFJJbVQrMUM5K21BNzFtbXlHYwp4SGZBYzVFQXhMTHNSL1hOa1MyU0NScXl2NHh1
    dERMSkFMbHI0ejdQYkVvQisvdGdWdkRTOGtFdm1DRHVCWjlUCm9tSDlBb0dCQU9teE5GRm84c3F4
    b092RVFQUm56a1h0SFFLVWR4K0xBa21rWTE3WjF2Qk5iVCs0bWxjVTY0NEoKbHBvK2o5dWdtUUFW
    L2JvWktMelVvS3RmMkZVemlVT3RGZmNHa3I1THNOSzNwZHQwcnVCaWZqejJwL1N2QVZoLwpWZXZS
    QjQ2SDkrME04SVJCaUdkaEtYR2tjV09ydG55WFZaTVozSzQ5UnZuUXVuRnlWRldLCi0tLS0tRU5E
    IFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

